services:
  sqlData:
    container_name: ThirdEyeHomeworkDB
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433