// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThirdEye.Homework.Persistence;

#nullable disable

namespace ThirdEye.Homework.Persistence.Migrations
{
    [DbContext(typeof(ThirdEyeHomeworkDbContext))]
    [Migration("20240511144834_AssetCashTypesForScenarioSpace")]
    partial class AssetCashTypesForScenarioSpace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThirdEye.Homework.Domain.Entities.ScenarioSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetClassCashType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScenarioSpaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c84c258-c05e-4a1a-862c-b9134c2f64e7"),
                            AssetClassCashType = "CS_EUR",
                            Name = "default_2c"
                        },
                        new
                        {
                            Id = new Guid("563d5378-ffa9-4675-be72-e3120ed3a759"),
                            AssetClassCashType = "CS_CHF",
                            Name = "chf_default_3a"
                        },
                        new
                        {
                            Id = new Guid("7590b66e-59cf-463a-a55c-e187deeb9111"),
                            AssetClassCashType = "CS_USD",
                            Name = "us_default_4b"
                        },
                        new
                        {
                            Id = new Guid("10b739f5-5f5f-4d15-86a7-518f64e2e7c6"),
                            AssetClassCashType = "CS_EUR",
                            Name = "dvv_3a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
